### ISSUE TITLE
Sporadic nested file lookup failure

### ISSUE THREAD

**Issue by NiceneNerd** [NiceneNerd/ukmm#120]
For no apparent reason, every once in a while while applying merges UKMM will fail to pull a nested file that is in the game dump, leading to the "no base version" or "no copy of X found in game dump or any mod" error. So far no reproducible conditions have been identified, though it seems to happen more often with Linkle than with other mods. This probably has something weird to do with caching and such, maybe? In any case, this issue is pinned for reference until it can be fixed.

**Comment by TheBiPerson** [comment]
[2023-05-17 10:39:44] INFO Started ukmm
[2023-05-17 10:39:45] INFO Initializing mod manager
[2023-05-17 10:39:45] INFO Current profile: Default
[2023-05-17 10:39:45] INFO Initializing deployment manager
[2023-05-17 10:39:45] INFO No files pending deployment
[2023-05-17 10:39:45] INFO Logger initialized
[2023-05-17 10:40:06] INFO Resetting pending deployment data
[2023-05-17 10:40:11] INFO Applying pending changes to mod configuration
[2023-05-17 10:40:11] INFO Applying changes
[2023-05-17 10:40:11] INFO Manifest not provided, remerging all mods
[2023-05-17 10:40:11] INFO Applying changes
[2023-05-17 10:40:11] INFO Unpacking game texts
[2023-05-17 10:40:14] ERROR Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/Armor_298_Upper.sbactorpack at `crates\uk-mod\src\unpack.rs@698:22`
    1: Failed to build file Actor/ActorLink/Armor_298_Upper.bxml for SARC at `crates\uk-mod\src\unpack.rs@720:18`
    2: No copy of Actor/ActorLink/Armor_298_Upper.bxml found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/ukmm/issues/120. at `crates\uk-mod\src\unpack.rs@637:14`

im not sure what to do, but ive posted it here now. it only happens when i press "refresh merge"

**Comment by NiceneNerd** [comment]
@TheBiPerson Is that with a Switch build of one or more Hyrule Rebalance modules?

**Comment by TheBiPerson** [comment]
Switch build with three hyrule rebalanced modules

**Comment by NiceneNerd** [comment]
Which modules? Can you check/tell if having one of the modules in particular enabled causes the error?

**Comment by TheBiPerson** [comment]
i have climate, beedle, and main enabled with proper priority. it seems to be main, if i disable beedle and leave climate it gives me the error, if i disable climate and leave beedle it gives me the error, and if i disable both it gives me the error. i also tried removing the mods entirely and running it without climate or beedle in the mod loader even when disabled and still got the error with just the main

**Comment by NiceneNerd** [comment]
So I finally did some investigating on Hyrule Rebalance for Switch and determined that the mod itself is the issue. The file `Actor/ActorLink/Armor_298_Upper.bxml` inside `Actor/Pack/Armor_298_Upper.sbactorpack` is broken.

**Comment by OsoaGH** [comment]
```
[2023-06-16 2:05:18] ERROR Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/Armor_298_Upper.sbactorpack at `crates\uk-mod\src\unpack.rs@781:22`
    1: Failed to build file Actor/ActorLink/Armor_298_Upper.bxml for SARC at `crates\uk-mod\src\unpack.rs@803:18`
    2: No copy of Actor/ActorLink/Armor_298_Upper.bxml found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/ukmm/issues/120. at `crates\uk-mod\src\unpack.rs@720:14`
```

Only happens when disabling the dye module in Hyrule Rebalance. Works fine with the dye module.

**Comment by NiceneNerd** [comment]
After disabling, does it persist if you refresh the merge?

**Comment by OsoaGH** [comment]
> After disabling, does it persist if you refresh the merge?

It does

**Comment by TheInvictusWolf** [comment]
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Pack/Dungeon104.pack at `crates\uk-mod\src\unpack.rs@781:22`
    1: Failed to build file Model/DgnMrgPrt_Dungeon104.Tex.sbfres for SARC at `crates\uk-mod\src\unpack.rs@803:18`
    2: No copy of Model/DgnMrgPrt_Dungeon104.Tex.sbfres found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/ukmm/issues/120. at `crates\uk-mod\src\unpack.rs@720:14`
    
I have randomizer and linkle mod but i get this whenever try refreshing merge and even after manually deploy, the game gets stuck loading.

**Comment by Mii-U** [comment]
Failed to apply pending mod changes

Caused by:
    No copy of Actor/Pack/Enemy_Ganon.sbactorpack found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/ukmm/issues/120. at `crates\uk-mod\src\unpack.rs@720:14`
    
    I verified my game files and redid the configuration and still got this error

**Comment by NiceneNerd** [comment]
@Mii-U What are your settings, and what mod(s) do you have?

**Comment by lisa-wolfgang** [comment]
I'm getting this error at the end of a slew of similar warnings:
<details close>
<summary>Click to expand</summary>
<br>

```
[2024-04-19 4:20:51] INFO Applying changes
[2024-04-19 4:20:51] INFO Unpacking game texts
[2024-04-19 4:20:51] WARN Failed to get Message/Msg_USen.product.sarc from Pack/Bootup_USen.pack//Message/Msg_USen.product.ssarc: Any(Failed to read Message/Msg_USen.product.sarc from SARC at path Pack/Bootup_USen.pack//Message/Msg_USen.product.ssarc at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/Bootup_USen.pack//Message/Msg_USen.product.ssarc at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/B-8/B-8_Static.mubin from Pack/AocMainField.pack//Map/MainField/B-8/B-8_Static.smubin: Any(Failed to read Map/MainField/B-8/B-8_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/B-8/B-8_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/B-8/B-8_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/I-3/I-3_Static.mubin from Pack/AocMainField.pack//Map/MainField/I-3/I-3_Static.smubin: Any(Failed to read Map/MainField/I-3/I-3_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/I-3/I-3_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/B-8/B-8_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/G-2/G-2_Static.mubin from Pack/AocMainField.pack//Map/MainField/G-2/G-2_Static.smubin: Any(Failed to read Map/MainField/G-2/G-2_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/G-2/G-2_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/G-2/G-2_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Actor/LifeCondition/Landmark200m.blifecondition from Pack/RemainsWater.pack//Actor/Pack/SoundOcclusionTagRemainsWater.sbactorpack//Actor/LifeCondition/Landmark200m.blifecondition: Any(Failed to read Actor/LifeCondition/Landmark200m.blifecondition from SARC at path Pack/RemainsWater.pack//Actor/Pack/SoundOcclusionTagRemainsWater.sbactorpack//Actor/LifeCondition/Landmark200m.blifecondition at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/RemainsWater.pack//Actor/Pack/SoundOcclusionTagRemainsWater.sbactorpack//Actor/LifeCondition/Landmark200m.blifecondition at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Actor/LifeCondition/Landmark200m.blifecondition from Pack/RemainsWater.pack//Actor/Pack/SoundOcclusionTagRemainsWater.sbactorpack//Actor/LifeCondition/Landmark200m.blifecondition: Any(Failed to read Actor/LifeCondition/Landmark200m.blifecondition from SARC at path Pack/RemainsWater.pack//Actor/Pack/SoundOcclusionTagRemainsWater.sbactorpack//Actor/LifeCondition/Landmark200m.blifecondition at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/RemainsWater.pack//Actor/Pack/SoundOcclusionTagRemainsWater.sbactorpack//Actor/LifeCondition/Landmark200m.blifecondition at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/C-1/C-1_Static.mubin from Pack/AocMainField.pack//Map/MainField/C-1/C-1_Static.smubin: Any(Failed to read Map/MainField/C-1/C-1_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/C-1/C-1_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/C-1/C-1_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/F-2/F-2_Static.mubin from Pack/AocMainField.pack//Map/MainField/F-2/F-2_Static.smubin: Any(Failed to read Map/MainField/F-2/F-2_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/F-2/F-2_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/C-1/C-1_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/H-1/H-1_Static.mubin from Pack/AocMainField.pack//Map/MainField/H-1/H-1_Static.smubin: Any(Failed to read Map/MainField/H-1/H-1_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/H-1/H-1_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/H-1/H-1_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/F-5/F-5_Static.mubin from Pack/AocMainField.pack//Map/MainField/F-5/F-5_Static.smubin: Any(Failed to read Map/MainField/F-5/F-5_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/F-5/F-5_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/F-5/F-5_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/CDungeon/Static.mubin from Pack/Bootup.pack//Map/CDungeon/Static.smubin: Any(Failed to read Map/CDungeon/Static.mubin from SARC at path Pack/Bootup.pack//Map/CDungeon/Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/Bootup.pack//Map/CDungeon/Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/G-3/G-3_Static.mubin from Pack/AocMainField.pack//Map/MainField/G-3/G-3_Static.smubin: Any(Failed to read Map/MainField/G-3/G-3_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/G-3/G-3_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/G-3/G-3_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/A-6/A-6_Static.mubin from Pack/AocMainField.pack//Map/MainField/A-6/A-6_Static.smubin: Any(Failed to read Map/MainField/A-6/A-6_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/A-6/A-6_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/A-6/A-6_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/H-3/H-3_Static.mubin from Pack/AocMainField.pack//Map/MainField/H-3/H-3_Static.smubin: Any(Failed to read Map/MainField/H-3/H-3_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/H-3/H-3_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/H-3/H-3_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/F-6/F-6_Static.mubin from Pack/AocMainField.pack//Map/MainField/F-6/F-6_Static.smubin: Any(Failed to read Map/MainField/F-6/F-6_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/F-6/F-6_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/F-6/F-6_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/C-2/C-2_Static.mubin from Pack/AocMainField.pack//Map/MainField/C-2/C-2_Static.smubin: Any(Failed to read Map/MainField/C-2/C-2_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/C-2/C-2_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/C-2/C-2_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/H-5/H-5_Static.mubin from Pack/AocMainField.pack//Map/MainField/H-5/H-5_Static.smubin: Any(Failed to read Map/MainField/H-5/H-5_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/H-5/H-5_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/H-5/H-5_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/B-3/B-3_Static.mubin from Pack/AocMainField.pack//Map/MainField/B-3/B-3_Static.smubin: Any(Failed to read Map/MainField/B-3/B-3_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/B-3/B-3_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/B-3/B-3_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/F-7/F-7_Static.mubin from Pack/AocMainField.pack//Map/MainField/F-7/F-7_Static.smubin: Any(Failed to read Map/MainField/F-7/F-7_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/F-7/F-7_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/F-7/F-7_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/I-4/I-4_Static.mubin from Pack/AocMainField.pack//Map/MainField/I-4/I-4_Static.smubin: Any(Failed to read Map/MainField/I-4/I-4_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/I-4/I-4_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/I-4/I-4_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/D-3/D-3_Static.mubin from Pack/AocMainField.pack//Map/MainField/D-3/D-3_Static.smubin: Any(Failed to read Map/MainField/D-3/D-3_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/D-3/D-3_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/D-3/D-3_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/G-5/G-5_Static.mubin from Pack/AocMainField.pack//Map/MainField/G-5/G-5_Static.smubin: Any(Failed to read Map/MainField/G-5/G-5_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/G-5/G-5_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/G-5/G-5_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/F-8/F-8_Static.mubin from Pack/AocMainField.pack//Map/MainField/F-8/F-8_Static.smubin: Any(Failed to read Map/MainField/F-8/F-8_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/F-8/F-8_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/F-8/F-8_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/H-7/H-7_Static.mubin from Pack/AocMainField.pack//Map/MainField/H-7/H-7_Static.smubin: Any(Failed to read Map/MainField/H-7/H-7_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/H-7/H-7_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/H-7/H-7_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/B-5/B-5_Static.mubin from Pack/AocMainField.pack//Map/MainField/B-5/B-5_Static.smubin: Any(Failed to read Map/MainField/B-5/B-5_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/B-5/B-5_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/B-5/B-5_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/C-4/C-4_Static.mubin from Pack/AocMainField.pack//Map/MainField/C-4/C-4_Static.smubin: Any(Failed to read Map/MainField/C-4/C-4_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/C-4/C-4_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/C-4/C-4_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/H-8/H-8_Static.mubin from Pack/AocMainField.pack//Map/MainField/H-8/H-8_Static.smubin: Any(Failed to read Map/MainField/H-8/H-8_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/H-8/H-8_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/H-8/H-8_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/B-6/B-6_Static.mubin from Pack/AocMainField.pack//Map/MainField/B-6/B-6_Static.smubin: Any(Failed to read Map/MainField/B-6/B-6_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/B-6/B-6_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/B-6/B-6_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/C-7/C-7_Static.mubin from Pack/AocMainField.pack//Map/MainField/C-7/C-7_Static.smubin: Any(Failed to read Map/MainField/C-7/C-7_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/C-7/C-7_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/C-7/C-7_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/E-4/E-4_Static.mubin from Pack/AocMainField.pack//Map/MainField/E-4/E-4_Static.smubin: Any(Failed to read Map/MainField/E-4/E-4_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/E-4/E-4_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/E-4/E-4_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/E-5/E-5_Static.mubin from Pack/AocMainField.pack//Map/MainField/E-5/E-5_Static.smubin: Any(Failed to read Map/MainField/E-5/E-5_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/E-5/E-5_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/E-5/E-5_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/C-8/C-8_Static.mubin from Pack/AocMainField.pack//Map/MainField/C-8/C-8_Static.smubin: Any(Failed to read Map/MainField/C-8/C-8_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/C-8/C-8_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/C-8/C-8_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/G-8/G-8_Static.mubin from Pack/AocMainField.pack//Map/MainField/G-8/G-8_Static.smubin: Any(Failed to read Map/MainField/G-8/G-8_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/G-8/G-8_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/G-8/G-8_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/G-6/G-6_Static.mubin from Pack/AocMainField.pack//Map/MainField/G-6/G-6_Static.smubin: Any(Failed to read Map/MainField/G-6/G-6_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/G-6/G-6_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/G-6/G-6_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/E-6/E-6_Static.mubin from Pack/AocMainField.pack//Map/MainField/E-6/E-6_Static.smubin: Any(Failed to read Map/MainField/E-6/E-6_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/E-6/E-6_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/E-6/E-6_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/I-7/I-7_Static.mubin from Pack/AocMainField.pack//Map/MainField/I-7/I-7_Static.smubin: Any(Failed to read Map/MainField/I-7/I-7_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/I-7/I-7_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/I-7/I-7_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Actor/AIProgram/MergedDungeonParts.baiprog from Pack/Dungeon134.pack//Actor/Pack/DgnMrgPrt_Dungeon134.sbactorpack//Actor/AIProgram/MergedDungeonParts.baiprog: Any(Failed to read Actor/AIProgram/MergedDungeonParts.baiprog from SARC at path Pack/Dungeon134.pack//Actor/Pack/DgnMrgPrt_Dungeon134.sbactorpack//Actor/AIProgram/MergedDungeonParts.baiprog at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/Dungeon134.pack//Actor/Pack/DgnMrgPrt_Dungeon134.sbactorpack//Actor/AIProgram/MergedDungeonParts.baiprog at `crates/uk-reader/src/lib.rs@241:74`)
[2024-04-19 4:20:51] WARN Failed to get Map/MainField/J-3/J-3_Static.mubin from Pack/AocMainField.pack//Map/MainField/J-3/J-3_Static.smubin: Any(Failed to read Map/MainField/J-3/J-3_Static.mubin from SARC at path Pack/AocMainField.pack//Map/MainField/J-3/J-3_Static.smubin at `crates/uk-reader/src/lib.rs@281:14`

Caused by:
    Failed to get parent for nested file at Pack/AocMainField.pack//Map/MainField/J-3/J-3_Static.smubin at `crates/uk-reader/src/lib.rs@241:74`)
```
</details>
The files that get these warnings/errors seem to be mostly random on each attempt.
I've double-checked that my dump path is set correctly and that said dump is valid.
The final error, also with seemingly random files every time:
<br>
<br>

```
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/TwnObj_HyruleCity_Slope_A_01C.sbactorpack at `crates/uk-mod/src/unpack.rs@781:22`
    1: Failed to build file Actor/LifeCondition/Landmark200m.blifecondition for SARC at `crates/uk-mod/src/unpack.rs@803:18`
    2: No copy of Actor/LifeCondition/Landmark200m.blifecondition found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates/uk-mod/src/unpack.rs@720:14`
```

**Comment by NiceneNerd** [comment]
@lisa-wolfgang It seems like all of these failures may involve DLC files, any possibility of something weird specifically with DLC in your dump? 

For that matter, what mod or mods does this happen with?

**Comment by lisa-wolfgang** [comment]
I don't believe there's anything abnormal about my DLC folder. This is happening on the latest commit of Second Wind.
Is it possible that this is a platform-specific issue? I'm on Ubuntu 23.10. Others have reportedly been able to get it built with their setups.

**Comment by lisa-wolfgang** [comment]
This also happens with the latest public release of Second Wind.

**Comment by lisa-wolfgang** [comment]
Resolved -- I found the actual cause and will be posting it in a separate issue.

**Comment by NiceneNerd** [comment]
Excellent news

**Comment by ilonachan** [comment]
Not to rain on the parade, but I just got this issue too.
```
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Pack/TitleBG.pack at `crates/uk-mod/src/unpack.rs@797:22`
    1: Failed to build file Model/Weapon_Arrow_001.Tex.sbfres for SARC at `crates/uk-mod/src/unpack.rs@819:18`
    2: No copy of Model/Weapon_Arrow_001.Tex.sbfres found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates/uk-mod/src/unpack.rs@736:14
```

To be fair, I'm pretty sure I've isolated it to the [Girly Animation Pack](https://gamebanana.com/mods/505453) mod. The weird thing is that previously this mod worked flawlessly! Restarting UKMM didn't fix it (that's why I'm here), but when I 1) unselected all other mods, 2) applied pending changes (and got the error), 3) rechecked all the other mods, 4) applied all changes again, the error went away! But it comes back if I change any options of, or unselect and reselect that specific mod. This seems like an edge case worth investigating to me.

In case it helps, here's my entire mod list right now:

1. [Linkle Mod for Switch](https://gamebanana.com/mods/246723) (tried this one bc [The Linkle Mod 3.0](https://gamebanana.com/mods/406768) doesn't actually load)
2. [Linkle Armor Stands](https://gamebanana.com/mods/246556)
3. [The Legend of Linkle Dialogue Mod NX](https://gamebanana.com/mods/442016)
4. [Girly Animation Pack](https://gamebanana.com/mods/505453) (which seems to be the main offender)
5. A manual repack of the [Linkle Armor Icon Pack for Switch](https://gamebanana.com/mods/33339)

And yes, my hyperfixation of today was that I saw a YT video and wanted to make Link as girl as possible, thanks for asking.

**Comment by t0mtee** [comment]
> ```
> [2023-06-16 2:05:18] ERROR Failed to apply pending mod changes
> 
> Caused by:
>     0: Failed to build SARC file Actor/Pack/Armor_298_Upper.sbactorpack at `crates\uk-mod\src\unpack.rs@781:22`
>     1: Failed to build file Actor/ActorLink/Armor_298_Upper.bxml for SARC at `crates\uk-mod\src\unpack.rs@803:18`
>     2: No copy of Actor/ActorLink/Armor_298_Upper.bxml found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to [https://github.com/NiceneNerd/ukmm/issues/120.](https://github.com/NiceneNerd/ukmm/issues/120.?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) at `crates\uk-mod\src\unpack.rs@720:14`
> ```
> 
> Only happens when disabling the dye module in Hyrule Rebalance. Works fine with the dye module.

This is still an issue for me - returning to the game and just found this error is persisting.

**Comment by NiceneNerd** [comment]
Is this with the Hyrule Rebalance dye module?

**Comment by t0mtee** [comment]
> Is this with the Hyrule Rebalance dye module?

Well the mod has split now and the dye module is now a seperate mod, but no I don't have the seperate mod installed.

**Comment by retcinder** [comment]
Also getting this issue with my (freshly dumped) EU copy of BoTW (Wii U) with only Second Wind (v1.9.14-alpha-6) enabled. The file it fails on changes randomly.

```
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/TBox_Field_Iron_Open.sbactorpack at `crates/uk-mod/src/unpack.rs@810:22`
    1: Failed to build file Actor/GeneralParamList/TBox.bgparamlist for SARC at `crates/uk-mod/src/unpack.rs@832:18`
    2: No copy of Actor/GeneralParamList/TBox.bgparamlist found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates/uk-mod/src/unpack.rs@749:14`
```

**Comment by battleforce404** [comment]
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/AOC_customs_0003.sbactorpack at `crates\uk-mod\src\unpack.rs@805:22`
    1: Failed to build file Physics/RigidBody/FldObj_HyliaStoneRuin_A/AOC_customs_0003.hkrb for SARC at `crates\uk-mod\src\unpack.rs@827:18`
    2: No copy of Physics/RigidBody/FldObj_HyliaStoneRuin_A/AOC_customs_0003.hkrb found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates\uk-mod\src\unpack.rs@744:14`

**Comment by battleforce404** [comment]
https://gamebanana.com/mods/149517

I'm getting the onedrive ones https://1drv.ms/u/s!AjFSMesz3_aKge1p6sh_zSdDayBMZQ?e=0M7v76 https://1drv.ms/u/s!AjFSMesz3_aKge1qTBEAI5oUIPgyrA?e=Zbmwbe

**Comment by battleforce404** [comment]
I tried the main mod files on the mod page and they worked just not the onedrive ones

the onedrive ones are different because they have hyrule castle restored

**Comment by t0mtee** [comment]
To anyone having issues with Hyrule Rebalance - take a look [here](https://gamebanana.com/posts/12277896). It was an issue with the mod itself, not UKMM.

**Comment by ChrisFratz** [comment]
So I'm trying to use Zelda's Ballad but I keep getting this error when trying to deploy it. Anybody know what I'm doing wrong?

```
Failed to apply pending mod changes at `src\gui\tasks.rs@182:10`

Caused by:
    0: Failed to build SARC file Pack/Bootup.pack at `crates\uk-mod\src\unpack.rs@810:22`
    1: Failed to build file Sound/Music/EnvPaletteReactiveBgm.bmscinfo for SARC at `crates\uk-mod\src\unpack.rs@832:18`
    2: No copy of Sound/Music/EnvPaletteReactiveBgm.bmscinfo found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates\uk-mod\src\unpack.rs@749:14`
```

**Comment by Contreth1313** [comment]
0. Failed to apply pending mod changes at `src\gui\tasks.rs@182:10`
1. Failed to build SARC file Actor/Pack/Item_FD.sbactorpack at `crates\uk-mod\src\unpack.rs@810:22`
2. Failed to build file Actor/AttClient/AutoAim_Obj45.batcl for SARC at `crates\uk-mod\src\unpack.rs@832:18`
3. No copy of Actor/AttClient/AutoAim_Obj45.batcl found in game dump or any mod. Sometimes this is a problem with the mod oryour game dump. However, it can also be a temporary cache error. If you know your dump and itsconfiguration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates\uk-mod\src\unpack.rs@749:14`

keeping getting these issues just using the botw randomizer mod by waikuteru

**Comment by BTAxis** [comment]
This issue persists with the [Hyrule Rebalance](https://gamebanana.com/mods/49532) mod, main module. No other mods in use. Using UKMM 0.17.0-1.

```
0. Failed to apply pending mod changes
1. Failed to build SARC file Actor/Pack/Armor_298_Upper.sbactorpack at `crates/uk-mod/src/unpack.rs@757:22`
2. Failed to build file Actor/ActorLink/Armor_298_Upper.bxml for SARC at `crates/uk-mod/src/unpack.rs@779:18`
3. No copy of Actor/ActorLink/Armor_298_Upper.bxml found in game dump or any mod. Sometimes this is a problem with the mod or your game dump. However, it can also be a temporary cache error. If you know your dump and its configuration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates/uk-mod/src/unpack.rs@694:14`
```

**Comment by t0mtee** [comment]
> This issue persists with the [Hyrule Rebalance](https://gamebanana.com/mods/49532) mod, main module. No other mods in use. Using UKMM 0.17.0-1.
> 
> ```
> 0. Failed to apply pending mod changes
> 1. Failed to build SARC file Actor/Pack/Armor_298_Upper.sbactorpack at `crates/uk-mod/src/unpack.rs@757:22`
> 2. Failed to build file Actor/ActorLink/Armor_298_Upper.bxml for SARC at `crates/uk-mod/src/unpack.rs@779:18`
> 3. No copy of Actor/ActorLink/Armor_298_Upper.bxml found in game dump or any mod. Sometimes this is a problem with the mod or your game dump. However, it can also be a temporary cache error. If you know your dump and its configuration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates/uk-mod/src/unpack.rs@694:14`
> ```

Try use my edited version of Hyrule Rebalance from [here](https://gamebanana.com/posts/12277896).

**Comment by XEDU96** [comment]
Dunno what causes this when trying to merge second wind
Have tried restarting ukmm
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Pack/Dungeon201.pack at `crates\uk-mod\src\unpack.rs@757:22`
    1: Failed to build file Actor/Pack/DgnMrgPrt_Dungeon201.sbactorpack for SARC at `crates\uk-mod\src\unpack.rs@779:18`
    2: Failed to build SARC file Actor/Pack/DgnMrgPrt_Dungeon201.sbactorpack at `crates\uk-mod\src\unpack.rs@757:22`
    3: Failed to build file Actor/AIProgram/MergedDungeonParts.baiprog for SARC at `crates\uk-mod\src\unpack.rs@779:18`
    4: No copy of Aoc/0010/Actor/AIProgram/MergedDungeonParts.baiprog found in game dump or any mod. Sometimes this is a problem with the mod or your game dump. However, it can also be a temporary cache error. If you know your dump and its configuration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates\uk-mod\src\unpack.rs@694:14`

**Comment by maxkmmorris-afk** [comment]
No copy of Actor/AIProgram/Armor.baiprog found in game dump or any mod

**Comment by manneymccoard-source** [comment]
0. Failed to apply pending mod changes
1. Failed to build SARC file Pack/Dungeon201.pack at `crates\uk-mod\src\unpack.rs@757:22`
2. Failed to build file Actor/Pack/DgnMrgPrt_Dungeon201.sbactorpack for SARC at `crates\uk-mod\src\unpack.rs@779:18`
3. Failed to build SARC file Actor/Pack/DgnMrgPrt_Dungeon201.sbactorpack at `crates\uk-mod\src\unpack.rs@757:22`
4. Failed to build file Actor/AIProgram/MergedDungeonParts.baiprog for SARC at `crates\uk-mod\src\unpack.rs@779:18`
5. No copy of Aoc/0010/Actor/AIProgram/MergedDungeonParts.baiprog found in game dump or any mod. Sometimes this is a problem with the mod or your game dump. However, it can also be a temporary cache error. If you know your dump and its configuration are sound, try restarting UKMM. If it persists, copy the error details and post as a comment to https://github.com/NiceneNerd/UKMM/issues/120. at `crates\uk-mod\src\unpack.rs@694:14`

I dont know how github works AT ALL but im putting this here. i dont know what to do and im quite agitated. i am using cemu and trying to play second wind, that is the only mod that i had loaded onto UKMM. please help
